
let guide_1_article_1_title = "Welcome to JayCom Help Central";
document.getElementById("guide-1-article-1-title").innerHTML = guide_1_article_1_title

let article_1_section_1_details = "Article 1 - date - minutes to read";
document.getElementById("article-1-section-1-details").innerHTML = article_1_section_1_details

//////////////////////////////////////////////////////////////////////////
let article_1_section_1_title = "Getting Started";
document.getElementById("article-1-section-1-title").innerHTML = article_1_section_1_title

let article_1_section_1_text = '"Section 1 Text" - Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio deleniti officiis voluptate magni id, sed consequuntur, temporibus eaque doloremque neque similique nihil, consequatur aliquam aperiam suscipit omnis. Nam placeat atque nesciunt at earum debitis adipisci soluta enim eos. Consectetur aperiam repellat iure voluptatem praesentium qui animi, sequi quas repudiandae laboriosam eum ullam. Voluptas veritatis dolore neque molestiae, consectetur inventore vel magnam a recusandae blanditiis delectus voluptatum dolor repellendus pariatur. Adipisci placeat cupiditate quae natus laboriosam exercitationem tempora magnam similique iusto ducimus. Est eligendi soluta minima ducimus ullam obcaecati exercitationem consequuntur sunt praesentium! Voluptas, autem doloremque! Eum provident vel earum dolor! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio deleniti officiis voluptate magni id, sed consequuntur, temporibus eaque doloremque neque similique nihil, consequatur aliquam aperiam suscipit omnis. Nam placeat atque nesciunt at earum debitis adipisci soluta enim eos. Consectetur aperiam repellat iure voluptatem praesentium qui animi, sequi quas repudiandae laboriosam eum ullam. Voluptas veritatis dolore neque molestiae, consectetur inventore vel magnam a recusandae blanditiis delectus voluptatum dolor repellendus pariatur. Adipisci placeat cupiditate quae natus laboriosam exercitationem tempora magnam similique iusto ducimus. Est eligendi soluta minima ducimus ullam obcaecati exercitationem consequuntur sunt praesentium! Voluptas, autem doloremque! Eum provident vel earum dolor! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio deleniti officiis voluptate magni id, sed consequuntur, temporibus eaque doloremque neque similique nihil, consequatur aliquam aperiam suscipit omnis. Nam placeat atque nesciunt at earum debitis adipisci soluta enim eos. Consectetur aperiam repellat iure voluptatem praesentium qui animi, sequi quas repudiandae laboriosam eum ullam. Voluptas veritatis dolore neque molestiae, consectetur inventore vel magnam a recusandae blanditiis delectus voluptatum dolor repellendus pariatur. Adipisci placeat cupiditate quae natus laboriosam exercitationem tempora magnam similique iusto ducimus. Est eligendi soluta minima ducimus ullam obcaecati exercitationem consequuntur sunt praesentium! Voluptas, autem doloremque! Eum provident vel earum dolor!';
document.getElementById("article-1-section-1-text").innerHTML = article_1_section_1_text

//////////////////////////////////////////////////////////////////////////
let article_1_section_2_title = "Section 2 Title";
document.getElementById("article-1-section-2-title").innerHTML = article_1_section_2_title

let article_1_section_2_text = "Section 2 Text - Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio deleniti officiis voluptate magni id, sed consequuntur, temporibus eaque doloremque neque similique nihil, consequatur aliquam aperiam suscipit omnis. Nam placeat atque nesciunt at earum debitis adipisci soluta enim eos. Consectetur aperiam repellat iure voluptatem praesentium qui animi, sequi quas repudiandae laboriosam eum ullam. Voluptas veritatis dolore neque molestiae, consectetur inventore vel magnam a recusandae blanditiis delectus voluptatum dolor repellendus pariatur. Adipisci placeat cupiditate quae natus laboriosam exercitationem tempora magnam similique iusto ducimus. Est eligendi soluta minima ducimus ullam obcaecati exercitationem consequuntur sunt praesentium! Voluptas, autem doloremque! Eum provident vel earum dolor!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio deleniti officiis voluptate magni id, sed consequuntur, temporibus eaque doloremque neque similique nihil, consequatur aliquam aperiam suscipit omnis. Nam placeat atque nesciunt at earum debitis adipisci soluta enim eos. Consectetur aperiam repellat iure voluptatem praesentium qui animi, sequi quas repudiandae laboriosam eum ullam. Voluptas veritatis dolore neque molestiae, consectetur inventore vel magnam a recusandae blanditiis delectus voluptatum dolor repellendus pariatur. Adipisci placeat cupiditate quae natus laboriosam exercitationem tempora magnam similique iusto ducimus. Est eligendi soluta minima ducimus ullam obcaecati exercitationem consequuntur sunt praesentium! Voluptas, autem doloremque! Eum provident vel earum dolor! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio deleniti officiis voluptate magni id, sed consequuntur, temporibus eaque doloremque neque similique nihil, consequatur aliquam aperiam suscipit omnis. Nam placeat atque nesciunt at earum debitis adipisci soluta enim eos. Consectetur aperiam repellat iure voluptatem praesentium qui animi, sequi quas repudiandae laboriosam eum ullam. Voluptas veritatis dolore neque molestiae, consectetur inventore vel magnam a recusandae blanditiis delectus voluptatum dolor repellendus pariatur. Adipisci placeat cupiditate quae natus laboriosam exercitationem tempora magnam similique iusto ducimus. Est eligendi soluta minima ducimus ullam obcaecati exercitationem consequuntur sunt praesentium! Voluptas, autem doloremque! Eum provident vel earum dolor! ";
document.getElementById("article-1-section-2-text").innerHTML = article_1_section_2_text

//////////////////////////////////////////////////////////////////////////////////
let article_1_section_3_title = "Section 3 Title";
document.getElementById("article-1-section-3-title").innerHTML = article_1_section_3_title

let article_1_other_text = "Other Stuff's Text - Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio deleniti officiis voluptate magni id, sed consequuntur, temporibus eaque doloremque neque similique nihil, consequatur aliquam aperiam suscipit omnis. Nam placeat atque nesciunt at earum debitis adipisci soluta enim eos. Consectetur aperiam repellat iure voluptatem praesentium qui animi, sequi quas repudiandae laboriosam eum ullam. Voluptas veritatis dolore neque molestiae, consectetur inventore vel magnam a recusandae blanditiis delectus voluptatum dolor repellendus pariatur. Adipisci placeat cupiditate quae natus laboriosam exercitationem tempora magnam similique iusto ducimus. Est eligendi soluta minima ducimus ullam obcaecati exercitationem consequuntur sunt praesentium! Voluptas, autem doloremque! Eum provident vel earum dolor! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio deleniti officiis voluptate magni id, sed consequuntur, temporibus eaque doloremque neque similique nihil, consequatur aliquam aperiam suscipit omnis. Nam placeat atque nesciunt at earum debitis adipisci soluta enim eos. Consectetur aperiam repellat iure voluptatem praesentium qui animi, sequi quas repudiandae laboriosam eum ullam. Voluptas veritatis dolore neque molestiae, consectetur inventore vel magnam a recusandae blanditiis delectus voluptatum dolor repellendus pariatur. Adipisci placeat cupiditate quae natus laboriosam exercitationem tempora magnam similique iusto ducimus. Est eligendi soluta minima ducimus ullam obcaecati exercitationem consequuntur sunt praesentium! Voluptas, autem doloremque! Eum provident vel earum dolor! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio deleniti officiis voluptate magni id, sed consequuntur, temporibus eaque doloremque neque similique nihil, consequatur aliquam aperiam suscipit omnis. Nam placeat atque nesciunt at earum debitis adipisci soluta enim eos. Consectetur aperiam repellat iure voluptatem praesentium qui animi, sequi quas repudiandae laboriosam eum ullam. Voluptas veritatis dolore neque molestiae, consectetur inventore vel magnam a recusandae blanditiis delectus voluptatum dolor repellendus pariatur. Adipisci placeat cupiditate quae natus laboriosam exercitationem tempora magnam similique iusto ducimus. Est eligendi soluta minima ducimus ullam obcaecati exercitationem consequuntur sunt praesentium! Voluptas, autem doloremque! Eum provident vel earum dolor!";
document.getElementById("article-1-section-3-text").innerHTML = article_1_other_text

/////////////////////////////////////////////////////////////////////////////////
let article_1_section_4_title = "Towering Peaks with Bob Ross";
document.getElementById("article-1-section-4-title").innerHTML = article_1_section_4_title

let article_1_section_4_text = "Other Stuff's Text - Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio deleniti officiis voluptate magni id, sed consequuntur, temporibus eaque doloremque neque similique nihil, consequatur aliquam aperiam suscipit omnis. Nam placeat atque nesciunt at earum debitis adipisci soluta enim eos. Consectetur aperiam repellat iure voluptatem praesentium qui animi, sequi quas repudiandae laboriosam eum ullam. Voluptas veritatis dolore neque molestiae, consectetur inventore vel magnam a recusandae blanditiis delectus voluptatum dolor repellendus pariatur. Adipisci placeat cupiditate quae natus laboriosam exercitationem tempora magnam similique iusto ducimus. Est eligendi soluta minima ducimus ullam obcaecati exercitationem consequuntur sunt praesentium! Voluptas, autem doloremque! Eum provident vel earum dolor! Other Stuff's Text - Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio deleniti officiis voluptate magni id, sed consequuntur, temporibus eaque doloremque neque similique nihil, consequatur aliquam aperiam suscipit omnis. Nam placeat atque nesciunt at earum debitis adipisci soluta enim eos. Consectetur aperiam repellat iure voluptatem praesentium qui animi, sequi quas repudiandae laboriosam eum ullam. Voluptas veritatis dolore neque molestiae, consectetur inventore vel magnam a recusandae blanditiis delectus voluptatum dolor repellendus pariatur. Adipisci placeat cupiditate quae natus laboriosam exercitationem tempora magnam similique iusto ducimus. Est eligendi soluta minima ducimus ullam obcaecati exercitationem consequuntur sunt praesentium! Voluptas, autem doloremque! Eum provident vel earum dolor! Other Stuff's Text - Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio deleniti officiis voluptate magni id, sed consequuntur, temporibus eaque doloremque neque similique nihil, consequatur aliquam aperiam suscipit omnis. Nam placeat atque nesciunt at earum debitis adipisci soluta enim eos. Consectetur aperiam repellat iure voluptatem praesentium qui animi, sequi quas repudiandae laboriosam eum ullam. Voluptas veritatis dolore neque molestiae, consectetur inventore vel magnam a recusandae blanditiis delectus voluptatum dolor repellendus pariatur. ";
document.getElementById("article-1-section-4-text").innerHTML = article_1_section_4_text


